function scrollToSection(){
    document.getElementById("content").scrollIntoView({
        behavior:"smooth"
    });
}

function showPopup(){
    document.getElementById("popup").style.display="flex";

    for(let i=0;i<30;i++){
        createHeart();
    }
}

function closePopup(){
    document.getElementById("popup").style.display="none";
}

function createHeart(){
    const heart=document.createElement("div");

    heart.className="heart";
    heart.innerHTML=["💖","💕","💜","🌸","✨"][Math.floor(Math.random()*5)];

    heart.style.left=Math.random()*100+"vw";
    heart.style.fontSize=(20+Math.random()*20)+"px";

    document.body.appendChild(heart);

    setTimeout(()=>heart.remove(),8000);
}

function loadImage(input){
    const file=input.files[0];
    if(!file) return;

    const reader=new FileReader();

    reader.onload=function(e){
        const box=input.parentElement;
        const img=box.querySelector("img");
        const placeholder=box.querySelector(".placeholder");

        img.src=e.target.result;
        img.style.display="block";
        placeholder.style.display="none";
    };

    reader.readAsDataURL(file);
}

const memories = [
    {
        title: "Romantic Moments",
        slides: [
            {
                src: "photo/pc9.jpg",
                caption: "Romantic Walk"
            },
            {
                src: "photo/pc8.jpg",
                caption: "Sunset Dinner"
            },
            {
                src: "photo/pc7.jpg",
                caption: "City Lights"
            },
            {
                 src: "photo/pc6.jpg",
                caption: "Park Picnic"
            },
            {
                src: "photo/pc5.jpg",
                caption: "Candlelight"
            }
        ]
    },
    {
        title: "Happy Adventures",
        slides: [
            {
                src: "photo/pc1.jpg",
                caption: "Romantic Walk"
            },
            {
                src: "photo/pc2.jpg",
                caption: "Sunset Dinner"
            },
            {
                src: "photo/pc3.jpg",
                caption: "City Lights"
            },
            {
                 src: "photo/pc4.jpg",
                caption: "Park Picnic"
            },
            {
                src: "photo/pc5.jpg",
                caption: "Candlelight"
            }
        ]
    },
    {
        title: "Sweet Celebrations",
        slides: [
            {
                src: "photo/pc9.jpg",
                caption: "Romantic Walk"
            },
            {
                src: "photo/pc8.jpg",
                caption: "Sunset Dinner"
            },
            {
                src: "photo/pc7.jpg",
                caption: "City Lights"
            },
            {
                 src: "photo/pc6.jpg",
                caption: "Park Picnic"
            },
            {
                src: "photo/pc5.jpg",
                caption: "Candlelight"
            }
        ]
    }
];

// If local photos are available in the `photo/` folder, use them for the first slide of each memory.
// This keeps the autogenerated SVG slides as fallbacks.
function tryUseLocalPhoto(path){
    return fetch(path, {method: 'HEAD'}).then(r=> r.ok).catch(()=>false);
}

tryUseLocalPhoto('photo/photo1.svg').then(exists=>{
    if(exists && memories[0] && memories[0].slides && memories[0].slides[0]){
        memories[0].slides[0].src = 'photo/pexels-leane-guex-60335201-7999852.jpg';
    }
});

tryUseLocalPhoto('photo/pexels-leane-guex-60335201-7999852.jpg').then(exists=>{
    if(exists && memories[1] && memories[1].slides && memories[1].slides[0]){
        memories[1].slides[0].src = 'photo/pexels-leane-guex-60335201-7999852.jpg';
    }
});

tryUseLocalPhoto('photo/photo3.svg').then(exists=>{
    if(exists && memories[2] && memories[2].slides && memories[2].slides[0]){
        memories[2].slides[0].img= 'photo/pexels-jan-van-der-wolf-11680885-37243405.jpg';
    }
});

tryUseLocalPhoto('photo/attached-image.jpg').then(exists=>{
    if(exists && memories[0] && memories[0].slides && memories[0].slides[1]){
        memories[0].slides[1].src = 'photo/attached-image.jpg';
        memories[0].slides[1].caption = 'A special photo for you';
    }
});

let activeMemoryIndex = 0;
let activeSlideIndex = 0;
let memoryTimer = null;

function updateMemorySlide(){
    const viewer = document.getElementById("memoryViewer");
    const image = document.getElementById("viewerImage");
    const title = document.getElementById("viewerTitle");
    const caption = document.getElementById("viewerCaption");
    const memory = memories[activeMemoryIndex];
    const slide = memory.slides[activeSlideIndex];

    title.textContent = memory.title;
    image.src = slide.src;
    image.alt = `${memory.title} slide ${activeSlideIndex + 1}`;
    caption.textContent = slide.caption;
}

function startMemoryTimer(){
    stopMemoryTimer();
    memoryTimer = setInterval(nextSlide, 300000); // 5 minutes
}

function stopMemoryTimer(){
    if(memoryTimer){
        clearInterval(memoryTimer);
        memoryTimer = null;
    }
}

function openMemoryViewer(index){
    activeMemoryIndex = index;
    activeSlideIndex = 0;
    updateMemorySlide();
    document.getElementById("memoryViewer").classList.remove("hidden");
    document.getElementById("memoryViewer").setAttribute("aria-hidden", "false");
    startMemoryTimer();
    startFireworks();
    startBalloons();
}

function closeMemoryViewer(){
    stopMemoryTimer();
    document.getElementById("memoryViewer").classList.add("hidden");
    document.getElementById("memoryViewer").setAttribute("aria-hidden", "true");
    stopFireworks();
    stopBalloons();
    // if the gallery was open before we showed the viewer, restore it
    if(window._wasGalleryOpen){
        openPhotoGallery();
        window._wasGalleryOpen = false;
    }
}

function nextSlide(){
    const memory = memories[activeMemoryIndex];
    activeSlideIndex = (activeSlideIndex + 1) % memory.slides.length;
    updateMemorySlide();
}

function prevSlide(){
    const memory = memories[activeMemoryIndex];
    activeSlideIndex = (activeSlideIndex - 1 + memory.slides.length) % memory.slides.length;
    updateMemorySlide();
    startMemoryTimer();
}

function openSurprise(){
    window.location.href = "surprise.html";
}

function openLove(){
    window.location.href = "Open.html";
}

function openPhotoGallery(){
    const gallery = document.getElementById('photoGallery');
    if(gallery){
        gallery.classList.remove('hidden');
    }
}

function closePhotoGallery(){
    const gallery = document.getElementById('photoGallery');
    if(gallery){
        gallery.classList.add('hidden');
    }
}

// Open any image in the existing memory viewer (re-uses overlay)
function openImageInViewer(src, title = ''){
    const image = document.getElementById('viewerImage');
    const viewerTitle = document.getElementById('viewerTitle');
    const viewerCaption = document.getElementById('viewerCaption');
    if(image){ image.src = src; image.alt = title || 'Photo'; }
    if(viewerTitle) viewerTitle.textContent = title || '';
    if(viewerCaption) viewerCaption.textContent = '';
    // remember if gallery was open, then close it
    const gallery = document.getElementById('photoGallery');
    const wasOpen = gallery && !gallery.classList.contains('hidden');
    window._wasGalleryOpen = !!wasOpen;
    if(wasOpen) gallery.classList.add('hidden');

    document.getElementById('memoryViewer').classList.remove('hidden');
    document.getElementById('memoryViewer').setAttribute('aria-hidden','false');
}

// Populate the photo grid with up to N images, trying common extensions.
function buildLargeGallery(count = 100){
    const grid = document.getElementById('photoGrid');
    if(!grid) return;
    grid.innerHTML = '';

    // List of actual files present in the photo/ folder (kept in sync with workspace)
    const photoFiles = [
        'photo/pc1.jpg', 'photo/pc2.jpg', 'photo/pc3.jpg', 'photo/pc4.jpg', 'photo/pc5.jpg',
        'photo/pc7.jpg', 'photo/pc8.jpg', 'photo/pc9.jpg',
        'photo/pexels-jan-van-der-wolf-11680885-37243405.jpg',
        'photo/pexels-leane-guex-60335201-7999852.jpg',
        'photo/pexels-semih-basaran-353570345-36413788.jpg'
    ];

    const filesToShow = photoFiles.slice(0, Math.min(count, photoFiles.length));

    filesToShow.forEach((src, idx) => {
        const wrapper = document.createElement('div');
        wrapper.className = 'rounded-2xl overflow-hidden bg-[#200032]';
        const img = document.createElement('img');
        img.className = 'w-full h-48 object-cover cursor-pointer transition-transform hover:scale-105';
        img.alt = `Photo ${idx+1}`;
        img.src = src;
        img.onerror = function(){ wrapper.style.display = 'none'; };
        img.onclick = function(){ openImageInViewer(img.src, img.alt); };
        wrapper.appendChild(img);
        grid.appendChild(wrapper);
    });
}

/* ⭐ STAR BACKGROUND ANIMATION */
document.addEventListener("DOMContentLoaded", ()=>{
    const canvas=document.getElementById("stars");
    const ctx=canvas.getContext("2d");

    function resize(){
        canvas.width=window.innerWidth;
        canvas.height=window.innerHeight;
    }
    resize();
    window.addEventListener("resize",resize);

    let stars=[];

    for(let i=0;i<200;i++){
        stars.push({
            x:Math.random()*window.innerWidth,
            y:Math.random()*window.innerHeight,
            r:Math.random()*1.8,
            speed:Math.random()*0.6+0.2
        });
    }

    function animate(){
        ctx.clearRect(0,0,canvas.width,canvas.height);

        for(let s of stars){
            ctx.beginPath();
            ctx.arc(s.x,s.y,s.r,0,Math.PI*2);
            ctx.fillStyle="white";
            ctx.fill();

            s.y += s.speed;

            if(s.y > canvas.height){
                s.y = 0;
                s.x = Math.random()*canvas.width;
            }
        }

        requestAnimationFrame(animate);
    }

    animate();
    // build gallery after stars animation init
    try{ buildLargeGallery(100); }catch(e){/* ignore */}
});

/* Fireworks and Balloons for memory viewer */
let fireworksAnimId = null;
let fireworksParticles = [];
let fireworksCtx = null;
let fireworksCanvas = null;
let fireworksInterval = null;

function initFireworks(){
    fireworksCanvas = document.getElementById('fireworksCanvas');
    if(!fireworksCanvas) return;
    fireworksCanvas.width = window.innerWidth;
    fireworksCanvas.height = window.innerHeight;
    fireworksCtx = fireworksCanvas.getContext('2d');
    window.addEventListener('resize', ()=>{
        if(fireworksCanvas){
            fireworksCanvas.width = window.innerWidth;
            fireworksCanvas.height = window.innerHeight;
        }
    });
}

function spawnFirework(){
    const x = Math.random()*window.innerWidth;
    const y = Math.random()*window.innerHeight*0.6 + window.innerHeight*0.2;
    const hue = Math.floor(Math.random()*360);
    const count = 30 + Math.floor(Math.random()*40);
    for(let i=0;i<count;i++){
        const angle = Math.random()*Math.PI*2;
        const speed = 2 + Math.random()*4;
        fireworksParticles.push({x,y,vx:Math.cos(angle)*speed, vy:Math.sin(angle)*speed, life:60+Math.random()*40, hue});
    }
}

function drawFireworks(){
    if(!fireworksCtx) return;
    fireworksCtx.fillStyle = 'rgba(0,0,0,0.15)';
    fireworksCtx.fillRect(0,0,fireworksCanvas.width,fireworksCanvas.height);

    for(let i=fireworksParticles.length-1;i>=0;i--){
        const p = fireworksParticles[i];
        p.x += p.vx;
        p.y += p.vy;
        p.vy += 0.03; // gravity
        p.life--;
        const alpha = Math.max(p.life/100,0);
        fireworksCtx.beginPath();
        fireworksCtx.fillStyle = `hsla(${p.hue},100%,60%,${alpha})`;
        fireworksCtx.arc(p.x,p.y,Math.max(1,alpha*3),0,Math.PI*2);
        fireworksCtx.fill();
        if(p.life<=0) fireworksParticles.splice(i,1);
    }
}

function fireworksLoop(){
    drawFireworks();
    fireworksAnimId = requestAnimationFrame(fireworksLoop);
}

function startFireworks(){
    initFireworks();
    if(fireworksInterval) clearInterval(fireworksInterval);
    spawnFirework();
    fireworksInterval = setInterval(spawnFirework, 700);
    if(!fireworksAnimId) fireworksLoop();
}

function stopFireworks(){
    if(fireworksInterval) { clearInterval(fireworksInterval); fireworksInterval=null; }
    if(fireworksAnimId){ cancelAnimationFrame(fireworksAnimId); fireworksAnimId=null; }
    if(fireworksCtx){ fireworksCtx.clearRect(0,0,fireworksCanvas.width,fireworksCanvas.height); }
    fireworksParticles = [];
}

/* Balloons */
let balloonInterval = null;
function startBalloons(){
    const container = document.getElementById('balloonContainer');
    if(!container) return;
    // spawn immediately then interval
    spawnBalloon(container);
    balloonInterval = setInterval(()=>spawnBalloon(container), 900);
}

function stopBalloons(){
    if(balloonInterval){ clearInterval(balloonInterval); balloonInterval = null; }
    const container = document.getElementById('balloonContainer');
    if(container){ container.innerHTML = ''; }
}

function spawnBalloon(container){
    const el = document.createElement('div');
    const size = 48 + Math.floor(Math.random()*60);
    el.className = 'balloon';
    el.style.width = size + 'px';
    el.style.height = Math.floor(size*1.15) + 'px';
    el.style.left = (10 + Math.random()*80) + '%';
    el.style.background = ['#ff6b6b','#ffd66b','#6bd6ff','#c98cff','#8cf57a'][Math.floor(Math.random()*5)];
    el.style.animationDuration = (5 + Math.random()*6) + 's';
    el.textContent = '🎈';
    container.appendChild(el);
    // remove after animation
    setTimeout(()=>{ if(el.parentElement) el.parentElement.removeChild(el); }, 13000);
}

// Viewer interaction: close on Escape and click outside content
document.addEventListener('keydown', (e)=>{
    if(e.key === 'Escape'){
        const viewer = document.getElementById('memoryViewer');
        const gallery = document.getElementById('photoGallery');
        if(gallery && gallery.classList && !gallery.classList.contains('hidden')){
            closePhotoGallery();
        } else if(viewer && viewer.classList && !viewer.classList.contains('hidden')){
            closeMemoryViewer();
        }
    }
});

const viewerElem = document.getElementById('memoryViewer');
if(viewerElem){
    viewerElem.addEventListener('click', (e)=>{
        if(e.target === viewerElem){
            closeMemoryViewer();
        }
    });
}

const photoGalleryElem = document.getElementById('photoGallery');
if(photoGalleryElem){
    photoGalleryElem.addEventListener('click', (e)=>{
        if(e.target === photoGalleryElem){
            closePhotoGallery();
        }
    });
}
